# Generated by Django 5.2.4 on 2025-07-15 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0002_juego_resena_delete_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='juego',
            name='estudio',
            field=models.CharField(default='Desconocido', max_length=150),
        ),
        migrations.AddField(
            model_name='juego',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(default='Sin descripción disponible'),
        ),
    ]
