# Generated by Django 5.2.4 on 2025-07-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0003_rename_titulo_juego_nombre_juego_estudio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('disparos', 'Disparos'), ('carrera', 'Carrera'), ('puzzles', 'Puzzles'), ('simulador_citas', 'Simulador de Citas'), ('dark_souls', 'Tipo Dark Souls'), ('metroidvania', 'Metroidvania'), ('cartas', 'Cartas'), ('deportes', 'Deportes'), ('terror', 'Terror'), ('coop', 'Cooperativo'), ('hack_slash', 'Hack and Slash')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AddField(
            model_name='juego',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='juegos', to='Tareas.categoria'),
        ),
    ]
