# Generated by Django 5.2.4 on 2025-07-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0004_categoria_juego_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la noticia', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción o resumen de la noticia')),
                ('url', models.URLField(help_text='URL completa hacia la noticia original')),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen (opcional)', null=True)),
                ('fuente', models.CharField(default='Admin', help_text='Fuente de la noticia', max_length=100)),
                ('destacada', models.BooleanField(default=True, help_text='Mostrar en página principal')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True, help_text='Noticia visible para usuarios')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
