# Generated by Django 5.2.4 on 2025-07-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0005_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del juego (opcional)', null=True, upload_to='juegos/'),
        ),
    ]
