# Generated by Django 5.2.4 on 2025-07-16 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0008_alter_juego_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juego',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveField(
            model_name='juego',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('disparos', 'Disparos'), ('carrera', 'Carrera'), ('puzzles', 'Puzzles'), ('rpg', 'RPG'), ('estrategia', 'Estrategia'), ('deportes', 'Deportes'), ('aventura', 'Aventura'), ('plataformas', 'Plataformas'), ('simulacion', 'Simulación'), ('mundo_abierto', 'Mundo Abierto'), ('terror', 'Terror'), ('coop', 'Cooperativo'), ('metroidvania', 'Metroidvania'), ('cartas', 'Cartas')], help_text='Selecciona una categoría para los juegos', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Selecciona las categorías que corresponden a este juego', to='Tareas.categoria'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tareas.juego'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='puntuacion',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')]),
        ),
    ]
