# Generated by Django 5.2.4 on 2025-07-16 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0009_alter_juego_options_remove_juego_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='Tareas.juego'),
        ),
    ]
